# coding: utf-8

"""
    Rainbow-API

    The responses of the open api in swagger focus on the data field rather than the code and the message fields  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from rainbowsdk.configuration import Configuration


class MultipartFileHeader(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'filename': 'str',
        'header': 'dict(str, list[str])',
        'size': 'int'
    }

    attribute_map = {
        'filename': 'filename',
        'header': 'header',
        'size': 'size'
    }

    def __init__(self, filename=None, header=None, size=None, local_vars_configuration=None):  # noqa: E501
        """MultipartFileHeader - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._filename = None
        self._header = None
        self._size = None
        self.discriminator = None

        if filename is not None:
            self.filename = filename
        if header is not None:
            self.header = header
        if size is not None:
            self.size = size

    @property
    def filename(self):
        """Gets the filename of this MultipartFileHeader.  # noqa: E501


        :return: The filename of this MultipartFileHeader.  # noqa: E501
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this MultipartFileHeader.


        :param filename: The filename of this MultipartFileHeader.  # noqa: E501
        :type filename: str
        """

        self._filename = filename

    @property
    def header(self):
        """Gets the header of this MultipartFileHeader.  # noqa: E501


        :return: The header of this MultipartFileHeader.  # noqa: E501
        :rtype: dict(str, list[str])
        """
        return self._header

    @header.setter
    def header(self, header):
        """Sets the header of this MultipartFileHeader.


        :param header: The header of this MultipartFileHeader.  # noqa: E501
        :type header: dict(str, list[str])
        """

        self._header = header

    @property
    def size(self):
        """Gets the size of this MultipartFileHeader.  # noqa: E501


        :return: The size of this MultipartFileHeader.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this MultipartFileHeader.


        :param size: The size of this MultipartFileHeader.  # noqa: E501
        :type size: int
        """

        self._size = size

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MultipartFileHeader):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MultipartFileHeader):
            return True

        return self.to_dict() != other.to_dict()
