# coding: utf-8

"""
    Rainbow-API

    The responses of the open api in swagger focus on the data field rather than the code and the message fields  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from rainbowsdk.configuration import Configuration


class ServicesTransferItemDto(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'amount': 'int',
        'token_id': 'str',
        'transfer_from_address': 'str',
        'transfer_to_address': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'token_id': 'token_id',
        'transfer_from_address': 'transfer_from_address',
        'transfer_to_address': 'transfer_to_address'
    }

    def __init__(self, amount=None, token_id=None, transfer_from_address=None, transfer_to_address=None, local_vars_configuration=None):  # noqa: E501
        """ServicesTransferItemDto - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._amount = None
        self._token_id = None
        self._transfer_from_address = None
        self._transfer_to_address = None
        self.discriminator = None

        if amount is not None:
            self.amount = amount
        self.token_id = token_id
        self.transfer_from_address = transfer_from_address
        self.transfer_to_address = transfer_to_address

    @property
    def amount(self):
        """Gets the amount of this ServicesTransferItemDto.  # noqa: E501


        :return: The amount of this ServicesTransferItemDto.  # noqa: E501
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ServicesTransferItemDto.


        :param amount: The amount of this ServicesTransferItemDto.  # noqa: E501
        :type amount: int
        """

        self._amount = amount

    @property
    def token_id(self):
        """Gets the token_id of this ServicesTransferItemDto.  # noqa: E501


        :return: The token_id of this ServicesTransferItemDto.  # noqa: E501
        :rtype: str
        """
        return self._token_id

    @token_id.setter
    def token_id(self, token_id):
        """Sets the token_id of this ServicesTransferItemDto.


        :param token_id: The token_id of this ServicesTransferItemDto.  # noqa: E501
        :type token_id: str
        """
        if self.local_vars_configuration.client_side_validation and token_id is None:  # noqa: E501
            raise ValueError("Invalid value for `token_id`, must not be `None`")  # noqa: E501

        self._token_id = token_id

    @property
    def transfer_from_address(self):
        """Gets the transfer_from_address of this ServicesTransferItemDto.  # noqa: E501


        :return: The transfer_from_address of this ServicesTransferItemDto.  # noqa: E501
        :rtype: str
        """
        return self._transfer_from_address

    @transfer_from_address.setter
    def transfer_from_address(self, transfer_from_address):
        """Sets the transfer_from_address of this ServicesTransferItemDto.


        :param transfer_from_address: The transfer_from_address of this ServicesTransferItemDto.  # noqa: E501
        :type transfer_from_address: str
        """
        if self.local_vars_configuration.client_side_validation and transfer_from_address is None:  # noqa: E501
            raise ValueError("Invalid value for `transfer_from_address`, must not be `None`")  # noqa: E501

        self._transfer_from_address = transfer_from_address

    @property
    def transfer_to_address(self):
        """Gets the transfer_to_address of this ServicesTransferItemDto.  # noqa: E501


        :return: The transfer_to_address of this ServicesTransferItemDto.  # noqa: E501
        :rtype: str
        """
        return self._transfer_to_address

    @transfer_to_address.setter
    def transfer_to_address(self, transfer_to_address):
        """Sets the transfer_to_address of this ServicesTransferItemDto.


        :param transfer_to_address: The transfer_to_address of this ServicesTransferItemDto.  # noqa: E501
        :type transfer_to_address: str
        """
        if self.local_vars_configuration.client_side_validation and transfer_to_address is None:  # noqa: E501
            raise ValueError("Invalid value for `transfer_to_address`, must not be `None`")  # noqa: E501

        self._transfer_to_address = transfer_to_address

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServicesTransferItemDto):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ServicesTransferItemDto):
            return True

        return self.to_dict() != other.to_dict()
