# coding: utf-8

"""
    Rainbow-API

    The responses of the open api in swagger focus on the data field rather than the code and the message fields  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rainbowsdk
from rainbowsdk.models.services_send_tx_resp import ServicesSendTxResp  # noqa: E501
from rainbowsdk.rest import ApiException

class TestServicesSendTxResp(unittest.TestCase):
    """ServicesSendTxResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ServicesSendTxResp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rainbowsdk.models.services_send_tx_resp.ServicesSendTxResp()  # noqa: E501
        if include_optional :
            return ServicesSendTxResp(
                tx_id = 56
            )
        else :
            return ServicesSendTxResp(
        )

    def testServicesSendTxResp(self):
        """Test ServicesSendTxResp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
