# coding: utf-8

"""
    Rainbow-API

    The responses of the open api in swagger focus on the data field rather than the code and the message fields  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rainbowsdk
from rainbowsdk.api.nfts_api import NFTsApi  # noqa: E501
from rainbowsdk.rest import ApiException


class TestNFTsApi(unittest.TestCase):
    """NFTsApi unit test stubs"""

    def setUp(self):
        self.api = rainbowsdk.api.nfts_api.NFTsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_n_ft_info(self):
        """Test case for n_ft_info

        Get NFT info, mainly owner and metadata  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
