# coding: utf-8

"""
    Rainbow-API

    The responses of the open api in swagger focus on the data field rather than the code and the message fields  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rainbowsdk
from rainbowsdk.models.services_mint_item_dto import ServicesMintItemDto  # noqa: E501
from rainbowsdk.rest import ApiException

class TestServicesMintItemDto(unittest.TestCase):
    """ServicesMintItemDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ServicesMintItemDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rainbowsdk.models.services_mint_item_dto.ServicesMintItemDto()  # noqa: E501
        if include_optional :
            return ServicesMintItemDto(
                amount = 56, 
                metadata_uri = '', 
                mint_to_address = '', 
                token_id = ''
            )
        else :
            return ServicesMintItemDto(
                mint_to_address = '',
        )

    def testServicesMintItemDto(self):
        """Test ServicesMintItemDto"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
