# coding: utf-8

"""
    Rainbow-API

    The responses of the open api in swagger focus on the data field rather than the code and the message fields  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rainbowsdk
from rainbowsdk.models.models_transaction import ModelsTransaction  # noqa: E501
from rainbowsdk.rest import ApiException

class TestModelsTransaction(unittest.TestCase):
    """ModelsTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ModelsTransaction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rainbowsdk.models.models_transaction.ModelsTransaction()  # noqa: E501
        if include_optional :
            return ModelsTransaction(
                chain_id = 56, 
                chain_type = 56, 
                created_at = '', 
                data = '', 
                deleted_at = rainbowsdk.models.gorm/deleted_at.gorm.DeletedAt(
                    time = '', 
                    valid = True, ), 
                epoch_height = 1.337, 
                epoch_number = 56, 
                error = '', 
                _from = '', 
                gas = 1.337, 
                gas_price = 1.337, 
                hash = '', 
                id = 56, 
                nonce = 56, 
                pending_reason = '', 
                state = 56, 
                storage_limit = 1.337, 
                task_type = 56, 
                to = '', 
                updated_at = '', 
                value = 1.337
            )
        else :
            return ModelsTransaction(
        )

    def testModelsTransaction(self):
        """Test ModelsTransaction"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
