# coding: utf-8

"""
    Rainbow-API

    The responses of the open api in swagger focus on the data field rather than the code and the message fields  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import rainbowsdk
from rainbowsdk.api.burns_api import BurnsApi  # noqa: E501
from rainbowsdk.rest import ApiException


class TestBurnsApi(unittest.TestCase):
    """BurnsApi unit test stubs"""

    def setUp(self):
        self.api = rainbowsdk.api.burns_api.BurnsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_burn_batch(self):
        """Test case for burn_batch

        Batch burn NFT  # noqa: E501
        """
        pass

    def test_burn_nft(self):
        """Test case for burn_nft

        Burn NFT  # noqa: E501
        """
        pass

    def test_get_burn_detail(self):
        """Test case for get_burn_detail

        Burn NFT detail  # noqa: E501
        """
        pass

    def test_get_burn_list(self):
        """Test case for get_burn_list

        Obtain the burned NFTs list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
