# coding: utf-8

"""
    Rainbow-API

    The responses of the open api in swagger focus on the data field rather than the code and the message fields  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import rainbowsdk
from rainbowsdk.models.services_set_sponsor_resp import ServicesSetSponsorResp  # noqa: E501
from rainbowsdk.rest import ApiException

class TestServicesSetSponsorResp(unittest.TestCase):
    """ServicesSetSponsorResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ServicesSetSponsorResp
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = rainbowsdk.models.services_set_sponsor_resp.ServicesSetSponsorResp()  # noqa: E501
        if include_optional :
            return ServicesSetSponsorResp(
                sponsor_collateral_tx_id = 56, 
                sponsor_gas_tx_id = 56
            )
        else :
            return ServicesSetSponsorResp(
        )

    def testServicesSetSponsorResp(self):
        """Test ServicesSetSponsorResp"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
