# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MiddlewaresAppLogin(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, app_id: str=None, app_secret: str=None):
        """MiddlewaresAppLogin - a model defined in OpenAPI

        :param app_id: The app_id of this MiddlewaresAppLogin.
        :param app_secret: The app_secret of this MiddlewaresAppLogin.
        """
        self.openapi_types = {
            'app_id': str,
            'app_secret': str
        }

        self.attribute_map = {
            'app_id': 'app_id',
            'app_secret': 'app_secret'
        }

        self._app_id = app_id
        self._app_secret = app_secret

    @classmethod
    def from_dict(cls, dikt: dict) -> 'MiddlewaresAppLogin':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The middlewares.appLogin of this MiddlewaresAppLogin.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app_id(self):
        """Gets the app_id of this MiddlewaresAppLogin.


        :return: The app_id of this MiddlewaresAppLogin.
        :rtype: str
        """
        return self._app_id

    @app_id.setter
    def app_id(self, app_id):
        """Sets the app_id of this MiddlewaresAppLogin.


        :param app_id: The app_id of this MiddlewaresAppLogin.
        :type app_id: str
        """
        if app_id is None:
            raise ValueError("Invalid value for `app_id`, must not be `None`")

        self._app_id = app_id

    @property
    def app_secret(self):
        """Gets the app_secret of this MiddlewaresAppLogin.


        :return: The app_secret of this MiddlewaresAppLogin.
        :rtype: str
        """
        return self._app_secret

    @app_secret.setter
    def app_secret(self, app_secret):
        """Sets the app_secret of this MiddlewaresAppLogin.


        :param app_secret: The app_secret of this MiddlewaresAppLogin.
        :type app_secret: str
        """
        if app_secret is None:
            raise ValueError("Invalid value for `app_secret`, must not be `None`")

        self._app_secret = app_secret
