# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class RainbowErrorsRainbowErrorDetailInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code: int=None, message: str=None):
        """RainbowErrorsRainbowErrorDetailInfo - a model defined in OpenAPI

        :param code: The code of this RainbowErrorsRainbowErrorDetailInfo.
        :param message: The message of this RainbowErrorsRainbowErrorDetailInfo.
        """
        self.openapi_types = {
            'code': int,
            'message': str
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message'
        }

        self._code = code
        self._message = message

    @classmethod
    def from_dict(cls, dikt: dict) -> 'RainbowErrorsRainbowErrorDetailInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The rainbow_errors.RainbowErrorDetailInfo of this RainbowErrorsRainbowErrorDetailInfo.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self):
        """Gets the code of this RainbowErrorsRainbowErrorDetailInfo.


        :return: The code of this RainbowErrorsRainbowErrorDetailInfo.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this RainbowErrorsRainbowErrorDetailInfo.


        :param code: The code of this RainbowErrorsRainbowErrorDetailInfo.
        :type code: int
        """

        self._code = code

    @property
    def message(self):
        """Gets the message of this RainbowErrorsRainbowErrorDetailInfo.


        :return: The message of this RainbowErrorsRainbowErrorDetailInfo.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this RainbowErrorsRainbowErrorDetailInfo.


        :param message: The message of this RainbowErrorsRainbowErrorDetailInfo.
        :type message: str
        """

        self._message = message
