# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ServicesBurnItemDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amount: int=None, token_id: str=None):
        """ServicesBurnItemDto - a model defined in OpenAPI

        :param amount: The amount of this ServicesBurnItemDto.
        :param token_id: The token_id of this ServicesBurnItemDto.
        """
        self.openapi_types = {
            'amount': int,
            'token_id': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'token_id': 'token_id'
        }

        self._amount = amount
        self._token_id = token_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ServicesBurnItemDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The services.BurnItemDto of this ServicesBurnItemDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self):
        """Gets the amount of this ServicesBurnItemDto.


        :return: The amount of this ServicesBurnItemDto.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ServicesBurnItemDto.


        :param amount: The amount of this ServicesBurnItemDto.
        :type amount: int
        """

        self._amount = amount

    @property
    def token_id(self):
        """Gets the token_id of this ServicesBurnItemDto.


        :return: The token_id of this ServicesBurnItemDto.
        :rtype: str
        """
        return self._token_id

    @token_id.setter
    def token_id(self, token_id):
        """Sets the token_id of this ServicesBurnItemDto.


        :param token_id: The token_id of this ServicesBurnItemDto.
        :type token_id: str
        """
        if token_id is None:
            raise ValueError("Invalid value for `token_id`, must not be `None`")

        self._token_id = token_id
