# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ServicesSendTxResp(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, tx_id: int=None):
        """ServicesSendTxResp - a model defined in OpenAPI

        :param tx_id: The tx_id of this ServicesSendTxResp.
        """
        self.openapi_types = {
            'tx_id': int
        }

        self.attribute_map = {
            'tx_id': 'tx_id'
        }

        self._tx_id = tx_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ServicesSendTxResp':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The services.SendTxResp of this ServicesSendTxResp.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def tx_id(self):
        """Gets the tx_id of this ServicesSendTxResp.


        :return: The tx_id of this ServicesSendTxResp.
        :rtype: int
        """
        return self._tx_id

    @tx_id.setter
    def tx_id(self, tx_id):
        """Sets the tx_id of this ServicesSendTxResp.


        :param tx_id: The tx_id of this ServicesSendTxResp.
        :type tx_id: int
        """

        self._tx_id = tx_id
