# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ServicesBurnDto(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, amount: int=None, chain: str=None, contract_address: str=None, contract_type: str=None, token_id: str=None, user: str=None):
        """ServicesBurnDto - a model defined in OpenAPI

        :param amount: The amount of this ServicesBurnDto.
        :param chain: The chain of this ServicesBurnDto.
        :param contract_address: The contract_address of this ServicesBurnDto.
        :param contract_type: The contract_type of this ServicesBurnDto.
        :param token_id: The token_id of this ServicesBurnDto.
        :param user: The user of this ServicesBurnDto.
        """
        self.openapi_types = {
            'amount': int,
            'chain': str,
            'contract_address': str,
            'contract_type': str,
            'token_id': str,
            'user': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'chain': 'chain',
            'contract_address': 'contract_address',
            'contract_type': 'contract_type',
            'token_id': 'token_id',
            'user': 'user'
        }

        self._amount = amount
        self._chain = chain
        self._contract_address = contract_address
        self._contract_type = contract_type
        self._token_id = token_id
        self._user = user

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ServicesBurnDto':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The services.BurnDto of this ServicesBurnDto.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self):
        """Gets the amount of this ServicesBurnDto.


        :return: The amount of this ServicesBurnDto.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ServicesBurnDto.


        :param amount: The amount of this ServicesBurnDto.
        :type amount: int
        """

        self._amount = amount

    @property
    def chain(self):
        """Gets the chain of this ServicesBurnDto.


        :return: The chain of this ServicesBurnDto.
        :rtype: str
        """
        return self._chain

    @chain.setter
    def chain(self, chain):
        """Sets the chain of this ServicesBurnDto.


        :param chain: The chain of this ServicesBurnDto.
        :type chain: str
        """
        allowed_values = ["conflux", "conflux_test"]  # noqa: E501
        if chain not in allowed_values:
            raise ValueError(
                "Invalid value for `chain` ({0}), must be one of {1}"
                .format(chain, allowed_values)
            )

        self._chain = chain

    @property
    def contract_address(self):
        """Gets the contract_address of this ServicesBurnDto.


        :return: The contract_address of this ServicesBurnDto.
        :rtype: str
        """
        return self._contract_address

    @contract_address.setter
    def contract_address(self, contract_address):
        """Sets the contract_address of this ServicesBurnDto.


        :param contract_address: The contract_address of this ServicesBurnDto.
        :type contract_address: str
        """
        if contract_address is None:
            raise ValueError("Invalid value for `contract_address`, must not be `None`")

        self._contract_address = contract_address

    @property
    def contract_type(self):
        """Gets the contract_type of this ServicesBurnDto.


        :return: The contract_type of this ServicesBurnDto.
        :rtype: str
        """
        return self._contract_type

    @contract_type.setter
    def contract_type(self, contract_type):
        """Sets the contract_type of this ServicesBurnDto.


        :param contract_type: The contract_type of this ServicesBurnDto.
        :type contract_type: str
        """
        allowed_values = ["erc721", "erc1155"]  # noqa: E501
        if contract_type not in allowed_values:
            raise ValueError(
                "Invalid value for `contract_type` ({0}), must be one of {1}"
                .format(contract_type, allowed_values)
            )

        self._contract_type = contract_type

    @property
    def token_id(self):
        """Gets the token_id of this ServicesBurnDto.


        :return: The token_id of this ServicesBurnDto.
        :rtype: str
        """
        return self._token_id

    @token_id.setter
    def token_id(self, token_id):
        """Sets the token_id of this ServicesBurnDto.


        :param token_id: The token_id of this ServicesBurnDto.
        :type token_id: str
        """
        if token_id is None:
            raise ValueError("Invalid value for `token_id`, must not be `None`")

        self._token_id = token_id

    @property
    def user(self):
        """Gets the user of this ServicesBurnDto.


        :return: The user of this ServicesBurnDto.
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this ServicesBurnDto.


        :param user: The user of this ServicesBurnDto.
        :type user: str
        """

        self._user = user
