# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ServicesSetSponsorResp(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, sponsor_collateral_tx_id: int=None, sponsor_gas_tx_id: int=None):
        """ServicesSetSponsorResp - a model defined in OpenAPI

        :param sponsor_collateral_tx_id: The sponsor_collateral_tx_id of this ServicesSetSponsorResp.
        :param sponsor_gas_tx_id: The sponsor_gas_tx_id of this ServicesSetSponsorResp.
        """
        self.openapi_types = {
            'sponsor_collateral_tx_id': int,
            'sponsor_gas_tx_id': int
        }

        self.attribute_map = {
            'sponsor_collateral_tx_id': 'sponsor_collateral_tx_id',
            'sponsor_gas_tx_id': 'sponsor_gas_tx_id'
        }

        self._sponsor_collateral_tx_id = sponsor_collateral_tx_id
        self._sponsor_gas_tx_id = sponsor_gas_tx_id

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ServicesSetSponsorResp':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The services.SetSponsorResp of this ServicesSetSponsorResp.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def sponsor_collateral_tx_id(self):
        """Gets the sponsor_collateral_tx_id of this ServicesSetSponsorResp.


        :return: The sponsor_collateral_tx_id of this ServicesSetSponsorResp.
        :rtype: int
        """
        return self._sponsor_collateral_tx_id

    @sponsor_collateral_tx_id.setter
    def sponsor_collateral_tx_id(self, sponsor_collateral_tx_id):
        """Sets the sponsor_collateral_tx_id of this ServicesSetSponsorResp.


        :param sponsor_collateral_tx_id: The sponsor_collateral_tx_id of this ServicesSetSponsorResp.
        :type sponsor_collateral_tx_id: int
        """

        self._sponsor_collateral_tx_id = sponsor_collateral_tx_id

    @property
    def sponsor_gas_tx_id(self):
        """Gets the sponsor_gas_tx_id of this ServicesSetSponsorResp.


        :return: The sponsor_gas_tx_id of this ServicesSetSponsorResp.
        :rtype: int
        """
        return self._sponsor_gas_tx_id

    @sponsor_gas_tx_id.setter
    def sponsor_gas_tx_id(self, sponsor_gas_tx_id):
        """Sets the sponsor_gas_tx_id of this ServicesSetSponsorResp.


        :param sponsor_gas_tx_id: The sponsor_gas_tx_id of this ServicesSetSponsorResp.
        :type sponsor_gas_tx_id: int
        """

        self._sponsor_gas_tx_id = sponsor_gas_tx_id
